## 예외처리

- 예외처리(exception handling)의 정의와 목적
    - 정의 : 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
    - 목적 : 프로그램의 비정상 종료를 막고 정상적인 실행상태를 유지하는 것

## 프로그램 오류

- 컴파일 에러(compile-time error) : 컴파일 할 때 발생하는 에러
    - javac.exe → 자바 컴파일러(프로그램에서 자동으로 해준다.)
    - 컴파일러의 역할
        - 구문 체크
        - 번역
        - 소스코드 최적화
        - 간단한 작업
- 런타임 에러(runtime error) : 실행 할 때 발생하는 에러
    - 에러(error) : 프로그램 코드에 의해서 수습 될 수 없는 심각한 오류
    - 예외(exception) : 프로그램 코드에 의해서 수습 될 수 있는 다소 미약한 오류
- 논리적 에러(logical error) : 작성 의도와 다르게 동작

### 예외 클래스의 계층 구조

<img width="902" alt="image" src="https://user-images.githubusercontent.com/108970153/199523423-84442dce-396b-4078-98f2-a46c6eee8823.png">

- Exception 클래스들 : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- RuntimeException 클래스들 : 프로그래머의 실수로 발생하는 예외

<img width="928" alt="image" src="https://user-images.githubusercontent.com/108970153/199523758-a044fbeb-d17d-407d-80ab-0ccaa77648a9.png">

### try-catch문

```java
try {
	// 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
	// Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception2 e2) {
	// Exception2이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (ExceptionN eN) {
	// ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}

// {} 생략 불가
```

- try-catch 문에서의 흐름
    - try 블럭 내에서 예외가 발생한 경우
        1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
        2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면 예외는 처리되지 못한다.
    - try 블럭 내에서 예외가 발생하지 않은 경우
        - catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
    - Exception이 선언된 catch 블럭은 모든 예외 처리(마지막 catch 블럭에 위치하는 것이 좋음)
    
    ```java
    class Ex8_4 {
    	public static void main(String args[]) {
    		System.out.println(1);			
    		System.out.println(2);
    		try {
    			System.out.println(3);
    			System.out.println(0/0);
    			System.out.println(4); 	// 실행되지 않는다.
    		} catch (ArithmeticException ae)	{
    			if (ae instanceof ArithmeticException) 
    				System.out.println("true");	
    			System.out.println("ArithmeticException");
    		} catch (Exception e){
    			System.out.println("Exception");
    		}	// try-catch의 끝
    		System.out.println(6);
    	}	// main메서드의 끝
    }
    ```
    

### printStackTrace() 와 getMessage()

- printStackTrace() : 예외 발생 당시의 호출스택(Call stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
- getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

```java
class Ex8_5 {
	public static void main(String args[]) {
		System.out.println(1);			
		System.out.println(2);

		try {
			System.out.println(3);
			System.out.println(0/0); // 예외발생!!!
			System.out.println(4);   // 실행되지 않는다.
		} catch (ArithmeticException ae)	{
			ae.printStackTrace();
			System.out.println("예외메시지 : " + ae.getMessage());
		}	// try-catch의 끝

		System.out.println(6);
	}	// main메서드의 끝
}
```

### 멀티 catch블럭

- 내용이 같은 catch블럭을 하나로 합친 것(JDK1.7부터)

```java
try {
	...
} catch (ExceptionA e) {
	e.printStackTrace();
} catch (ExceptionB e2) {
	e2.printStackTrace();
}
```

→

```java
try {
	...
} catch (ExceptionA | ExceptionB e) {
	e.printStackTrace();
} 
```

- 멀티 catch에 쓰는 두 클래스가 부모 자식 관계면 안된다.
- 두 클래스의 공통 멤버만 사용가능
    - if문으로 형변환시 비공통 멤버 사용 가능하지만 비추천

### 예외 발생시키기

- 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든다
    - Exception e = new Exception(”고의로 발생시켰음”);
- 키워드 throw를 이용해서 예외를 발생시킨다.
    - throw e;
    
    ```java
    class Ex8_6 {
    	public static void main(String args[]) {
    		try {
    			Exception e = new Exception("고의로 발생시켰음.");
    			throw e;	 // 예외를 발생시킴
    		//  throw new Exception("고의로 발생시켰음.");
    
    		} catch (Exception e)	{
    			System.out.println("에러 메시지 : " + e.getMessage());
    			e.printStackTrace();
    		}
    		System.out.println("프로그램이 정상 종료되었음.");
    	}
    }
    ```
    

### checked예외, unchecked예외

- checked예외 : 컴파일러가 예외 처리 여부를 체크(예외 처리 필수)
    - Exception 과 그 자손 클래스
- unchecked예외 : 컴파일러가 예외 처리 여부를 체크 안함(예외 처리 선택)
    - RuntimeException 과 그 자손
    - 필수로 예외처리를 해야하게된다면 거의 모든 코드에 예외처리를 해야하기 때문

### 메서드에 예외 선언하기

- 예외를 처리하는 방법 : try-catch문, 예외 선언하기, 은폐하기
- 메서드가 호출시 발생가능한 예외를 호출하는 쪽에 알리는 것
- 예외를 발생시키는 키워드 : throw
예외를 메서드에 선언할 때 쓰이는 키워드 : throws

```java
class Ex8_9 {
	public static void main(String[] args) throws Exception {
		method1();	 // 같은 클래스내의 static멤버이므로 객체생성없이 직접 호출가능.
  	}	// main메서드의 끝

	static void method1() throws Exception {
		method2();
	}	// method1의 끝

	static void method2() throws Exception {
		throw new Exception();
	}	// method2의 끝
}
```

<img width="960" alt="image" src="https://user-images.githubusercontent.com/108970153/199524019-101a1298-612a-4c0e-ad3c-1db05062d96f.png">

- JVM이 받아서 기본 예외처리
    - 예외가 발생한 호출스택 예외처리
    
    ```java
    Exception in thread "main" java.lang.Exception
    	at Ex8_9.method2(Ex8_9.java:11)
    	at Ex8_9.method1(Ex8_9.java:7)
    	at Ex8_9.main(Ex8_9.java:3)
    ```
    

### finally 블럭

- 예외 발생여부와 관계없이 수행되어야 하는 코드를 넣는다.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/108970153/199524224-e3daca0f-5e66-45d7-9bac-41e9e675d104.png">

### 사용자 정의 예외 만들기

- 우리가 직접 예외 클래스를 정의 할 수 있다.
- 조상은 Exception과 RuntimeException 중에서 선택

```java
class MyException extends Exception {
	MyException(String msg) { // 문자열을 매개변수로 받는 생성자
		super(msg); // 조상인 Exception 클래스의 생성자를 호출한다.
	}
}
```

### 예외 되던지기(exception re-throwing)

- 예외를 처리한 후에 다시 예외를 발생시키는 것
- 호출한 메서드와 호출된 메서드 양쪽 모두에서 예외처리 하는 것

```java
class Ex8_12 {
	public static void main(String[] args) {
		try  {
			method1();		
		} catch (Exception e)	{
			System.out.println("main메서드에서 예외가 처리되었습니다.");
		}
	}	// main메서드의 끝

	static void method1() throws Exception {
		try {
			throw new Exception();
		} catch (Exception e) {
			System.out.println("method1메서드에서 예외가 처리되었습니다.");
			throw e;			// 다시 예외를 발생시킨다.
		}
	}	// method1메서드의 끝
}
```

### 연결된 예외(chained exception)

- 한 예외가 다른 예외를 발생시킬 수 있다.
- 예외 A가 예외 B를 발생시키면, A는 B의 원인 예외(cause exception)

> Throwable initCause(Throwable cause) : 지정한 예외를 원인 예외로 등록
Throwable getCause() : 원인 예외를 반환
> 

```java
public class Throwable implements Seriallizable {
	...
	private Throwable cause = this; // 객체 자신(this)을 원인 예외로 등록
	...
	public synchronized Throwable initCause(Throwable cause) {
		...
			this.cause = cause; // cause를 원인 예외로 등록
			return this;
	}
		...
}
```

사용 이유

- 여러 예외를 하나로 묶어서 다루기 위해서
- checked예외를 unchecked 예외로 변경하려 할 때 사용
    - 필수처리 → 선택처리
